FROM nginx

RUN rm /etc/nginx/conf.d/default.conf
ADD easylearn-site.conf /etc/nginx/conf.d/easylearn-site.conf

RUN mkdir -p /var/www/build
ADD build /var/www/build
RUN chown -R www-data:www-data /var/www/
RUN chmod -R 755 /var/www/

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]
